### PR TITLE
Assembly guide

### PR DESCRIPTION
**Pull request by daveismith**
Merge the assembly guide to master so we can keep it in line with that release and start to take smaller PRs to update the docs.

### CODE REVIEW

**Comment by daveismith** [comment]
Note: I cancelled the checks so that they didn't generate new MOBO and STL files which is unnecessary for this.

**Review by stuartpittaway — APPROVED** [review]
Looks good to me.

**Review by G-Pereira — CHANGES_REQUESTED** [review]
This needs to be rebased to manually solve each conflict, there's a lot of them :s can you do it @daveismith ?

**Comment by daveismith** [comment]
@G-Pereira - It's fine to merge, just not to rebase. I've manually dealt with all of the conflicts already.

**Review by G-Pereira — APPROVED** [review]
LGTM then!

**Pull request merged**
