### PR TITLE
Schematic improvement proposal

### PR DESCRIPTION
**Pull request by ZOUDIO**
Discord
@jessevdz

Fixes:
- Proper hierarchical structure
Label inside the sheets with their local name
Then connect them together at sheet-level.
- Split into functional blocks
Just like with software its good to have one function per group of components.
For example: the power input, reverse polarity protection, buckconverter, multiplexer and LDO
were connected as one block. Now they are split into their functional blocks.
- Used smaller symbols
Some symbols used their large variant, which looks a bit funny in normal schematics
For example some R's have been changed to R_Small's.
- Align symbols to grid
A lot of the symbols were off the default 50mil grid.

And a lot of other general fixes in readability and structure.
Electrically the schematic should be the same.
Improvements that would require a schematic change can possibly
be done later in a seperate commit.

Schematic is not ready for direct merge (pins not connected, references missing).
If wanted, I can finish it and make it ready to merge.

### CODE REVIEW

**Comment by goncalo-pereira-builtcolab** [comment]
Hey! I like what you did with the schematic I think it looks so much nicer and more importantly it is so much easier to read. I also agree with using the default grid in order to be easier to route things without having to have very precise mouse movement or zoom in a lot.

Having that said, it is far easier to wait for rev03 is released and no more changes on our side are required before you carry on your work. I don't think you need to start over. If I were you, when we get rev03 released, I would store all the sch files from your branch, then discard your changes and fork again. Then, on a clean fork, copy your files over and update the layout from the schematic (without applying changes!) to detect changes on component values (because that's only what will change from this point on). And then update your schematic until no schematic changes are detected from the KiCAD's PCB layout tool.

What do you think @ZOUDIO ?

**Comment by G-Pereira** [comment]
Hey! I like what you did with the schematic I think it looks so much nicer and more importantly it is so much easier to read. I also agree with using the default grid in order to be easier to route things without having to have very precise mouse movement or zoom in a lot.

Having that said, it is far easier to wait for rev03 is released and no more changes on our side are required before you carry on your work. I don't think you need to start over. If I were you, when we get rev03 released, I would store all the sch files from your branch, then discard your changes and fork again. Then, on a clean fork, copy your files over and update the layout from the schematic (without applying changes!) to detect changes on component values (because that's only what will change from this point on). And then update your schematic until no schematic changes are detected from the KiCAD's PCB layout tool.

What do you think @ZOUDIO ?

**Comment by ZOUDIO** [comment]
Hello @G-Pereira ! When is the planned release of REV3? As long as the electrical connectivity stays the same, it should be safe to refactor the schematics. If you do it after the release commit, people that want to look at or improve the schematics will be looking in the old schematics.

After refactoring I also have some other small improvements that improve performance and useability. It would be nice to get the REV3 as close to perfect as possible, but in the interest of time I would understand if such things are put aside for future revisions.

**Comment by G-Pereira** [comment]
There's no hard deadline but is definitely about to happen.

About changing features we are not taking feature improvements at this point. For the moment it is probably best to describe those as GitHub Issues in order to discuss them for future revisions.
Also check GitHub projects to see what's already on the plans for rev04

**Comment by ZOUDIO** [comment]
Let me know if you want to proceed with applying (some of the) schematic refactoring before REV3. I have experience with it, and think it can be done with almost no risk as long as we check it against the current layout. Its just nice to have a clean release instead of a bunch of post-release fixups. But you can make the judgment better, since you're ofcourse more deeply involved in the project than me. Im available for a Discord call if you want to talk about a strategy on how to do this.

Some of the other issues I spotted:
- I guess JP25 is meant to disable D1? But shorting DRV to ground does not seem like good practice. Also, why even bother having an option to disable it anyway?
- JP26 is a bit confusing. If you want to it properly it should be done with a power mux like TPS2113A which selects the 5V from the buck whenever present, and otherwise grabs the 5V from the USB.
Even if you dont use a power mux, you could just remove the jumper and always install both diodes.
- The gate of U11 is too close to its maximum for 24V operation.
Gates are pretty sensitive. If its damaged by a voltage spike the whole board wont power on.
I would recommend at least a voltage divider there, but the best is a 10V zener + resistor.
- Some symbols are retrieved from a rescue library
They should be merged with the main symbol library for neatness.
- A fuse on the USB power and a common mode filter in the USB datalines would be good practice, but not strictly necessary.
- If the design has all step files defined, STEP export can be added to KiBot as an artifact
This can be nice to keep the PCB mechanically aligned with the rest of the project.
- Defining order codes for different shops should not be done in the KiCad design file
This should be done externally via an ERP system or tools like Octopart.
KiCad should only contain a manufacturer partnumber. This way its also easier to keep the core design files correct without all these ordercodes.
If people want to know where to order, the easiest way is to load the KiBom export in Octopart. This will give you a shopping list at all the best/cheapest stores.

Other than that I have not done a deep dive in all details of the design yet.
But if others have been using it succesfully I guess the basics are okay.
I really like the project in general.
Now that 3D printers have entered the toolkit of the hobbyist, pnp machines should too :)

**Comment by G-Pereira** [comment]
As you might have noticed mobo rev03 has been released!

>     * I guess JP25 is meant to disable D1? But shorting DRV to ground does not seem like good practice. Also, why even bother having an option to disable it anyway?

you've got it wrong. D1 and R23 are marked as DNP on the default config for that reason JP25 is a closed solder jumper in case people want to populate it and in that case they need to cut JP25. It's not populated by default to reduce BOM cost

>     * JP26 is a bit confusing. If you want to it properly it should be done with a power mux like TPS2113A which selects the 5V from the buck whenever present, and otherwise grabs the 5V from the USB.
>       Even if you dont use a power mux, you could just remove the jumper and always install both diodes.

Those diodes are meant to allow a very niche use case where you want to power the board (except the 12/24V and the USB A ports) out of USB. Because it is a niche target group we followed the cheaper and simpler approach. Also, those aren't populated by default to reduce BOM cost.

>     * The gate of U11 is too close to its maximum for 24V operation.
>       Gates are pretty sensitive. If its damaged by a voltage spike the whole board wont power on.
>       I would recommend at least a voltage divider there, but the best is a 10V zener + resistor.

FDS4435BZ has built-in zenners on the gate


>     * Some symbols are retrieved from a rescue library
>       They should be merged with the main symbol library for neatness.

If was the case it was a mistake! I've checked now and it seems to have been fixed now (probably Stephen)

>     * A fuse on the USB power and a common mode filter in the USB datalines would be good practice, but not strictly necessary.

This has been considered but removed to reduce BOM cost.



>     * If the design has all step files defined, STEP export can be added to KiBot as an artifact
>       This can be nice to keep the PCB mechanically aligned with the rest of the project.

we are using KiCAD Stepup FreeCAD plugin for now, same thing



>     * Defining order codes for different shops should not be done in the KiCad design file
>       This should be done externally via an ERP system or tools like Octopart.
>       KiCad should only contain a manufacturer partnumber. This way its also easier to keep the core design files correct without all these ordercodes.
>       If people want to know where to order, the easiest way is to load the KiBom export in Octopart. This will give you a shopping list at all the best/cheapest stores.

Theoretically, I agree but this way we've been doing is working really great. Maybe we can find another way soon that is equally easy to maintain and to provide to people.

Thank you for your work! It looks great!

**Comment by ZOUDIO** [comment]
I saw it, congrats on the release :)

> FDS4435BZ has built-in zenners on the gate

Maybe I am missing something, but it seems the diode on the gate is a TVS for ESD protection.

And with regards to things like status leds and being able to power via USB, 
there is also a benefit to easy debugging and ease of use. 
Having multiple bom types can be a pain to keep track of.
Once you hit production, cost of things like diodes and leds are very low.

Anyway, I also understand your reasoning.

Let me know if you want to pull my schematic, then I will finish refactoring.

**Comment by G-Pereira** [comment]
> Maybe I am missing something, but it seems the diode on the gate is a TVS for ESD protection.

You are right! Let's get that fixed on next release. We were planning to change it already because the device should heat up a lot if one stresses all stepper motors.



> Let me know if you want to pull my schematic, then I will finish refactoring.

I already did! If you don't make any changes to the board itself other than readability changes (which they look amazing) we can get this merged really quick to master!

**Comment by G-Pereira** [comment]
Feel free to continue this, but make sure absolutely no changes are done to the PCB! I'll make sure the mobo files aren't touched until you are finished and this is merged :)

**Comment by ZOUDIO** [comment]
Okay great! I will finish it over the coming week, you can expect the pull request beginning of next week.

**Comment by goncalo-pereira-builtcolab** [comment]
Ok!

**Comment by ZOUDIO** [comment]
It's actually the mobo-rev03-schematic-improvement branch that contains the version that should be merged. I will try to rebase it to the mobo-rev03 branch that's actually referenced in this pull request. I'm trying to work out this Git thing, please bear with me :)

It will probably be ready in about 2 days, but I will mark it "Ready for review" by then.

**Comment by G-Pereira** [comment]
Great to hear! I think we'll get notified once you do that, be sure to refresh the review request to be sure. Looks so nice, thanks a lot!

**Comment by G-Pereira** [comment]
While trying to pull this PR several conflicts arise from git that can not easily be merged. Could you apply this to the current state of the master branch? We have not touched the design files for the mobo since you have started this PR, is it possible that your fork was already a little old when you have started working on this?

**Comment by G-Pereira** [comment]
By separately pulling your fork I have also noticed you aren't keeping the designators intact which forces the PCB layout to be out of sync with the components on the schematic. This also needs to be fixed so this can be merged.

**Comment by ZOUDIO** [comment]
Can you have another look at the reference designators? Those should not have changed. If you update the lay-out, you have to enable "Re-associate footprints by reference", otherwise it updates by timestamp. But if you do that the lay-out should be in sync with the schematic. 

Once that is verified, I can have a look at basing it on the most recent files.

**Comment by G-Pereira** [comment]
You are correct, sorry to mislead you. I have meant to use that option but must have forgotten it. The PCB is syncing correctly. Go ahead with rebasing your work from master. If I were you, I would create a clean fork out of the master branch, delete every .sch in there related to the mobo, copy your files over, and then check if the PCB syncs correctly. At least this sounds like the easiest way to do this. The KiCAD project file doesn't seem to track which .sch there are, they only have dependencies between each .sch file.

**Comment by ZOUDIO** [comment]
FYI: I'm quite busy at the moment, it will probably be the first week of Januari when I have the time to fix this.

**Comment by ZOUDIO** [comment]
@G-Pereira I'm going to pick this up again in the coming weeks. Do you want to stay in KiCad 5 or is it better to transistion to 6.0 now?

**Comment by G-Pereira** [comment]
Hello! We are currently migrating to v6. Please wait to get that settled first otherwise it will be a mess :)

**Comment by G-Pereira** [comment]
You can follow PR #426 and wait for it to be merged

**Comment by ZOUDIO** [comment]
Ah okay great, just subscribed to the PR. Maybe it's good to close this PR, and once the designs have transistioned to V6, make a clean fork including PR.

**Comment by G-Pereira** [comment]
Definitely agree.

**Pull request closed without merging**
