### PR TITLE
Motherboard schematic improvement

### PR DESCRIPTION
**Pull request by ZOUDIO**
Follow-up on https://github.com/index-machines/index/pull/365
This time in Kicad 6 @G-Pereira

**Description:**

I saw some possibilities for improvement, starting with the motherboard schematic.
This pull request does not contain changes that affect the actual lay-out.
Those improvements will be addressed seperately, so things do not get mixed up.

**Changelog:**

- Fixed ERC issues
Some symbol links were broken, probably due to the transition to Kicad 6.
ERC log is now clean.

- Replaced some big symbols with their small variant
Looks more in proportion to the rest of the components.

- Moved some of the power flags
Power flags should be placed on points where power comes in or is generated.

- General clean-up
Like moving symbol fields in a readable location and making sure all symbols are on-grid.

- Applied proper hierarchical structuring
Just like in software, you want one purpose per function (in this case per sheet).
Also like in software, you do not want unnecessary global variables (in this case nets).
So all subcircuits are contained in a sheet, and only the nets that are connected to other subcircuits are exposed via hierarchical labels.

- Renamed nets for consistency
Within an hierarchical schematic you name the nets according to their local function.
What they are connected to is made clear in a higher-level sheet.

- Repeated sub-circuits are put into sheets.
This way circuits can be used in multiple instances, without having to draw the circuit multiple times.
This was already done for the mosfets and motors, but is now also applied to the vacuum sensors and aux headers.

How to check if connectivity has not changed?
As can be seen in the commits, the PCB files has not changed.
Currently they lay-out is full of DRC errors, probably due to the Kicad 6 transition.
There are some solder jumpers, silkscreen and loose tracks that are the source of the problems.
To fix this:
1) Temporarily change all jumpers with bridges to open jumpers
2) Under file > board setup > violation severity: ignore silkscreen overlap and silkscreen clipped by soldermask.
3) Under file > board setup > constraints: decrease copper to hole clearance to 0.2mm.
4) Under file > board setup > Net Classes: decrease clearance and track width to 0.15mm
5) Under tools > cleanup tracks and vias: only check 'delete tracks unconnected at one end' and click 'update pcb'.
6) DRC should now be clean
7) Under tools > Update PCB from schematic: check all options and run

DRC should now still be clean, indicating the connectivity of the schematic has stayed the same.

If you see something that seems wrong to you, or unclear, let me know.
Then I can push changes/fixes to my repo before you pull.

Cheers,
Jesse

### CODE REVIEW

**Comment by G-Pereira** [comment]
This looks good to be merged, thank you! Right now with kits going out the door the merging process takes a little longer, don't worry if you don't see this merged in the next days, it is not forgotten

**Comment by G-Pereira** [comment]
Thank you! I will track this inside the repo and get it merged to master.

**Comment by ZOUDIO** [comment]
I saw that you already synced it with the PCB and got it DRC free, nice!

Now that the schematic is clean, I have a list of improvements that will alter the schematic and/or lay-out. 
Where is the best place to post this? Make an issue on Github?

There are some other KiCad projects in the Lumen I see. 
For example, I could apply the same structuring and improvements to the feeder mobo.
If this would help the project out, let me know. I am happy to help.

**Comment by G-Pereira** [comment]
Yes, listing the suggestions on a GitHub issue seems a good idea.

Don't worry about feeders right now, we are going to change some things around as we are developing a new version of them right now

**Pull request merged**
