### PR TITLE
Belt Tensioning Update and Mechanical BOM Refresh

### LINKED ISSUE #79: Emboss Part Number into FDM Parts
To help identify parts and their revisions after they've been printed, it'd be great to emboss the part number into a vertical wall on most/all of the FDM parts. If possible, automating this in FreeCAD somehow would be ideal.

### LINKED ISSUE #155: [CAD] - back legs need cable management
The rear legs have no good mechanism to route the cables for the stepper motors back to the mobo. There should be channels or attachment points for zip ties to allow the wires to come down to the lower 2020 extrusion so the can be run back to the mobo.

### LINKED ISSUE #221: [CAD] - Add Z-Axis idler Spacer to Repo
A spacer for the z-axis idler doesn't exist in the cad but is something a number of builders have needed to add to their builds. One was posted in discord at [https://discord.com/channels/688723670461448225/739250421893300264/796448153565790248](https://discord.com/channels/688723670461448225/739250421893300264/796448153565790248). It should be added to the git repo and assembly.

### LINKED ISSUE #229: [CAD] - Tensioning system for X/Y/Z Belts
In Order to get better precision, a belt tensioning system should be added. For the Y-Axis this should be added onto the front Index leg (opposite side of stepper motor)

however, as some people already printed the complete index frame (me included) I modeled a quick addon. This tensioner can be used instead of any existing belt clamp. (Intended for use on Y-Axis, NOT X-Axis!)
unknown

the left arrows point to two slots where two M3 nuts are inserted. Between the right blocks is a M3 screw. which has some 7x3x3 bearings onto it. A stack of M3 spacers also can be used instead of bearings.

.step an STL's attached, use it at your own risk!
[Tensioner_Fix.zip](https://github.com/sphawes/index/files/6192890/Tensioner_Fix.zip)

Edit: tension the belt, then 
move the axis and only after moving check the tensioning strength of the belt!

### LINKED ISSUE #299: [CAD] - Part numbering for 0025 - duplicated in 3d Print folder
In the FDM folder there are two folders named
* FDM-0025-00_pump-mount
* FDM-0027-00_belt-clamp

when the 3D-Prints folder is built (from the Assembly file)

FDM-0027 doesn't exist, FDM_0025_00_belt_clamp.stl and FDM_0025_00_pump_mount.stl have the same "0025" id

### LINKED ISSUE #312: [CAD] - suggestion - wider belt holes
Widening (horizontal) all the belt holes a bit (gantry and such), to make the belt easier to swap after assembly.

DISCORD: ["Could you make the gantry belt holes bigger, as in horizontal length? I personally do not see what it could harm (please tell me if I'm wrong), and that would be really helpful to swap/mount belts without removing whole gantry and the -just calibrated- distance to the rollers"](https://discordapp.com/channels/688723670461448225/814870897722523699/841691881384837140)

### PR DESCRIPTION
**Pull request by sphawes**
Hey all!

Here's a monster PR with all the recent CAD updates, along with an updated mechanical Bill of Materials. Here is what is included:

- Fixed improper method of building files in FreeCAD, now only basing sketches off of Datum Planes
- All belts have fine tension adjustment, either through a screw adjustment or a slotted holes for a stepper motor mount (Closes #229)
- All roller gantries have fine tensioning on both sides of the bolt holding the third roller
- All fasteners are included in the assembly file, generated by the Fastener workbench
- Standardized passthrough and threading diameters for holes in printed parts, and dimensions for press-fit nuts have been tuned
- All printed parts have a Datum Plane named `PrintPlane` that defines the intended plane upon which they should be printed
- All printed parts have a ShapeString named `PN` who's value is the part number of the part, including the revision number (eg `FDM-0023-02`). In the parts that have the space for it, this is embossed in the part. Closes #79 
- Added separate, non-broken part for the back right leg to reduce confusion if it's the same as the back left leg (it no longer is to help remove this confusion; they are unique now).
- Misc CAD improvements, like better fits of parts and ease of assembly. Closes #312, Closes #299, Closes #221, Closes #155 
- Updated Mechanical Bill of Materials.
- Updated README mainly to direct people to the wiki for most things and update the hero image (not really relevant to the rest of this, but it needed to happen).

Would love to hear your thoughts on this stuff!

### CODE REVIEW

**Comment by daveismith** [comment]
@sphawes - I'll have to look at this more closely tonight, but did you manage to get the chamfer we talked about in the dev meeting in? I don't think we had a ticket and I didn't see it in the description.

**Review by daveismith — COMMENTED** [review]
- [ ] In the assembly, only the FDM-0017_z-gantry-left part is present. However, the limit switch on the right hand side of the x gantry needs a z-gantry on the right to trigger. This part should be in the assembly and should be exported by the various scripts so users can print it.

- [ ] Missing fastener info for the mobo
- [ ] Pulley on the Y motors cannot be adjusted while the motor is installed. Consider putting a cutout like on the x motor mount.
- [ ] The M3x16 bolt used to tension the Y axis seems like it may cause interference with the Z axis if the v-slot wheel isn't near the top of the slot.
- [ ] The mount for the various nozzle tips isn't in the assembly, and as such the necessary fasteners are also not accounted for.

**Comment by ocouch** [comment]
For the hero image, missed a spot in the bottom left leg and a tiny bit of touch up.
Also made a transparent PNG, so it looks good on dark mode too.

https://github.com/ocouch/index/blob/master/img/index-hero.jpg
https://github.com/ocouch/index/blob/master/img/index-hero.png

**Comment by stuartpittaway** [comment]
I've printed a number of these 3d parts from @sphawes branch already - generally printed fine.

**Comment by G-Pereira** [comment]
- [ ] We are still using A2Plus workbench, any strong reason not to upgrade to Assembly4? (would fix #153)
- [ ] Mobo can be included using KiCAD StepUp plugin directly from the .kicad_pcb file.
- [ ] Feeders could be included as well to get a sense of the space they occupy up to the plate.
- [ ] At this point we already settled on the power supply requirements since the most power-consuming devices are already in so it would be ideal to have a mount for the Meanwell LRS-350-24
- [ ] If we rotate the pump 90 degrees the tube would fit better since the wires can make that 90 degree angle easier than the tube.
- [ ] Performing this rotation lets us mount a second pump side by side
- [ ] We have settled on using 3-way valves that although we haven't tested them yet Jason recommends them so in my opinion that's enough to design a mount for a 3V1-06 Solenoid Valve.
- [ ] The part number embossing is being done with a font referenced to a path on Stephen's machine. The font license should be checked and if possible it should be added to the repo so a relative path can be set.
- [ ] Holes are done using a pocket feature at least on FDM-0001, using the Hole feature would be beneficial which allows setting the type of hole namely if it is a screw-in or a clerance hole.

**Comment by stuartpittaway** [comment]
I noticed the pocket Vs hole issue as well.

The BOM also references a vacuum pump from Amazon which is 12V, is this correct in the context of the meanwell supply at 24V? Or does the new mobo step that down?

**Comment by G-Pereira** [comment]
@sphawes I've noticed that the z-idler spacer in the assembly is referenced to **./FDM/z-idler-spacer.FCStd** but should instead be **./FDM/FDM-0038_z-idler-spacer.FCStd**

**Comment by G-Pereira** [comment]
Closed and reopened to trigger CI

**Comment by G-Pereira** [comment]
I have thought about some things more and I think this PR should be the frame we'll use on our MVP:
- [ ] The rotation motor needs some way of cable management to the umbilical.
- [ ] The stagging plate holes need to be changed to M3 (make sure you use the hole feature!) they are currently 2.75mm (screwable M3 I think which would ruin coating)
- [ ] Bottom camera is missing and so are its mounting screws
- [ ] The screws that mount the head to the linear rails can easily be ISO4762 if the screw head hole is inserted 0.5mm more. This allows using the same supplier (for example AliExpress listing) for all screws. But that's not the only case, there are several screw standards on the design. For example, the M5 ISO7380 could be replaced by ISO4762.
- [ ] The crew head types should be kept to a minimum so we can later include the least number of screwdrivers on the kit for people to assemble! These highlighted in green have different head types.

image

- [ ] The tube coupling on the head doesn't seem a good point to save cost by having a fixed coupling. When the head rotates the torsion introduced can push the gantry assembly and make it move slightly since we are using wheel rollers and those are a little elastic and over time, when the rollers get some slack, this movement can be quite noticeable especially on finer pitch components like MCUs.
- [ ] Meanwell provides a CAD file for the PSU [LRS-350-3D.zip](https://github.com/index-machines/index/files/6564492/LRS-350-3D.zip) which could be included on the assembly
- [ ] Getting wiring on the assembly would help sourcing wire lengths using [this tutorial](https://www.youtube.com/watch?v=qXxmO_nvUX0) this can also be used for umbilicals and vacuum tubing!
- [ ] For splitting the vacuum to the vacuum sensors I have tested these ones with success (they don't noticeably leak) and they are insanely available!
image

**Comment by sphawes** [comment]
Alright, here's some comments and updates about changes I made! Thank you for all for the notes!

- Added a new part and part number for z-gantry-right (FDM-0039) and should export normally. It's also been added to the assembly.
- Added fasteners and standoffs for mounting the mobo
- Added cutout to Y motor mounts so the pulley can be adjusted after the motors have been mounted
- The M3x16 bolt has fit well with a good amount of clearance in my experience printing it out, so I've left that unchanged. There's an M3x14 in the BOM already so if we do need to shorten it, it'll be easy to do so without adding a new unique part.
- Added nozzle tip holster and necessary mounting hardware
- As for the assembly workbench used, I have no strong feelings about using A2Plus instead of A4, but that's a pretty low priority to do the conversion, given that A2Plus is working alright as is. If folks would like to take a crack at upgrading, I'd be happy to take a look.
- In regards to importing the Mobo and other ECAD items, this update is purely for getting the mechanical BOM in order. We'll focus on getting ring light, mobo, power supply, cable harnesses, and other things included in a later update. Feeders will likely not be included at all, as they're a customizable item and not part of the base machine. 
- I've rearranged the pump to have a better orientation for tubing and routing to the new pneumatic Y splitter that replaces the manifold part (FDM-0018). There's now space for two pumps.
- For the 3-way valves, we'll model them and add them into the assembly once we've validated that they work.
- I've gone through and updated the font reference path to be relative in the repository, so it should work on anyone's machine. The font is licensed through the [Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0).
- Similar to the Assembly workbench change, it is currently not worth the effort to switch all pocket features to hole features, but if someone would like to make that contribution I'd be happy to merge it!
- Wiring from the rotation motor has cable management not reflected in the assembly that will become more apparent when cable harness drawings are made.
- I've double checked the staging plate hole diameters and have confirmed that they're 3.4mm.
- Added bottom camera and mounting hardware
- Fixed erroneous Torx head hardware that got added by accident, switching all instances to ISO4762.
- The thickness of the plastic where the Z carriage gets mounted is already quite thin, so I'd prefer not to make it any thinner. Changing the type of screw wouldn't reduce the unique part count anyway, given that we don't already have an M3 short enough for this application. I also want to keep the corner brackets to aluminum because they are the only metal feature mounting the aluminum extrusion together, and that extra rigidity is worth an extra hardware BOM item.
- The amount of force a static tube coupling to the top of the rotation motor exerts on the system is very little. Many folks use this system without issue, and with enough tubing for free rotation, it should work just fine.
- Updated the BOM to reflect all these changes

**Comment by G-Pereira** [comment]
What are we going to do about the automatic exports? @Jnesselr and I have looked into it and the script works on both our machines but it fails on the CI. @sphawes and @daveismith want to give it a try?

**Comment by stuartpittaway** [comment]
> What are we going to do about the automatic exports? @Jnesselr and I have looked into it and the script works on both our machines but it fails on the CI. @sphawes and @daveismith want to give it a try?

I mentioned on another thread that this script is hardcoded to only processes a single file...

 FDM-0015_down-light-mount.FCStd

Looks like a test/debug version

**Comment by G-Pereira** [comment]
> > What are we going to do about the automatic exports? @Jnesselr and I have looked into it and the script works on both our machines but it fails on the CI. @sphawes and @daveismith want to give it a try?
> 
> I mentioned on another thread that this script is hardcoded to only processes a single file...
> 
> FDM-0015_down-light-mount.FCStd
> 
> Looks like a test/debug version

Yes, I did that but we removed that last week, it doesn't change the fact that it doesn't work :)

**Comment by daveismith** [comment]
I would suggest we get Stephen’s changes merged so someone like yourself ,
Justin, or me can try to work with the latest files when attempting to
adjust scripts. I would say it needs to be fixed before it gets merged.

**Comment by stuartpittaway** [comment]
> > > What are we going to do about the automatic exports? @Jnesselr and I have looked into it and the script works on both our machines but it fails on the CI. @sphawes and @daveismith want to give it a try?
> > 
> > 
> > I mentioned on another thread that this script is hardcoded to only processes a single file...
> > FDM-0015_down-light-mount.FCStd
> > Looks like a test/debug version
> 
> Yes, I did that but we removed that last week, it doesn't change the fact that it doesn't work :)

Ok, it didn't look like it when viewing the GitHub action runs.

I think I also got this BODY error when python opens a freecad file which is just a mirror part, like the front legs.

The mirrors don't appear to have a body, or it's in a different place in the object model.

**Comment by Jnesselr** [comment]
I can verify that a mirrored part doesn't have an object named "Body". FDM-0002_front-right-leg.FCStd has "Body (FDM-0001 Copy)" and "Body (FDM-0001 Copy) (Mirror #1)".

- [ ] Rename "Body (FDM-0001 Copy) (Mirror #1)" in "FDM-0002_front-right-leg.FCStd" to "Body"

Aside from not being able to determine the orientation of the part via the print plane (which Stephen said he'd update in another diff in case we needed to verify the math), that's the only issue as far as the export script goes.

**Comment by sphawes** [comment]
I went through and made sure that there is at least one object titled "Body" in each part, updated the assembly, and for the life of me cannot figure out why it keeps failing, and on a random part like FDM-0015_down-light-mount.FCStd no less. It seems identical to all the other parts as far as I can tell. I think we should merge this into index-machines/cad-pn, and figure out what the hell is going on in another PR.

**Comment by Jnesselr** [comment]
I just merged #325. I think you have to rebase to get the latest export script. If there's no conflicts and you're ready to land, I say let's land this puppy and sort it all out if it's still failing then.

**Review by Jnesselr — APPROVED** [review]

**Pull request merged**
