### PR TITLE
Add kitspace manifest

### PR DESCRIPTION
**Pull request by kasbah**
Hey, this PR adds a kitspace.yaml manifest file which lets you add the project to [kitspace.org](https://kitspace.org). 

The idea of Kitspace is to make it as easy as possible to (re-)build an electronics design by automating the add-to cart functionality, providing automatic generation of an assembly guide through Interactive HTML BOM, providing easy access to the BOM, specs and Gerber files and more. 

Here are some preview of what the pages will look like:

- [mobo](http://add-index-pnp.preview.kitspace.org/boards/github.com/kitspace-forks/index/index_mobo/)
- [piggyback](http://add-index-pnp.preview.kitspace.org/boards/github.com/kitspace-forks/index/index_piggyback/)
- [ringLight](http://add-index-pnp.preview.kitspace.org/boards/github.com/kitspace-forks/index/index_ringLight/)

The BOM isn't ideal yet, if we had some .csv or excel files with the parts, digikey and/or mouser etc SKUs, and references in one then you'de get the 1-click BOM add to cart functionality. Right now I am just pulling out basic BOM info from the .kicad_pcb file actually. (The one .csv file I found for the piggyback, doesn't have any schematic references in it.)

Anyway, let me know if you are happy to add it to Kitspace. Happy to help nail down the BOM thing as well, I actually develop a tool for that called the [BOM Builder](https://kitspace.org/bom-builder/) and I can give you access if you want to try it out.

### CODE REVIEW

**Review by raouldeheer — APPROVED** [review]

**Comment by sphawes** [comment]
hey @kasbah! sorry for the huge delay on this!

as you mentioned, the BOM for this whole project is pretty nonexistent. right now things are changing fast enough that it isn't worth keeping a fully accurate BOM all the time, but once the basics are nailed down and changes to the BOM aren't significant, i could see this being a cool way to help folks build one. I'll put this PR on hold for now but revisit once we have a true stable release. thanks for making this, and awesome site!

**Comment by G-Pereira** [comment]
Hi @kasbah ! Right now we have several automatic exports that I am wondering if we are able to use kitspace for loading them into fab houses. For example, we have the gerbers on each of the pcb folders and also the BOMs that can be used for SMT services. Is kitspace able to load all this files and setup a PCB order with SMT service from this files?

**Comment by kasbah** [comment]
Not yet unfortunately. It is our plan to implement something like that but right now you can only export to distributor carts. Choosing LCSC parts, that can be used for JLC Assembly, is the closest thing we currently support.

**Comment by G-Pereira** [comment]
Ok, thank you!

**Comment by G-Pereira** [comment]
Hey @kasbah ! Can you change this to include our generated Gerber's instead or the kicad project?

**Comment by kasbah** [comment]
We could do this by just adding `gerbers: gerber-folder/` fields in the yaml but I don't see any generated Gerbers in this repo.

**Comment by daveismith** [comment]
It's in the mobo-rev03 and feeder-rev05 branches in the export folder contained under each PCB project. There's a zip file containing all the gerbers and a gerbers folder. There are also BOM and placement files generated as part of the export.

For example, the mobo export right now are at https://github.com/sphawes/index/tree/mobo-rev03/pnp/pcb/mobo/export but I think you may need to wait until it merges to the main branch.

**Comment by kasbah** [comment]
Thanks @daveismith, currently with the way Kitspace works all the Gerbers have to be on a single branch, preferably main or master, and extracted to a folder, not in a zip.

**Comment by G-Pereira** [comment]
Great! @kasbah we will get back to you when we merge our feeder and mobo revisions to master

**Pull request closed without merging**
