### PR TITLE
feat: Adds initial manual relrefs to make glossary items linkable

### PR DESCRIPTION
**Pull request by darigovresearch**
Follows from discussion in #261

### CODE REVIEW

**Comment by daveismith** [comment]
I don't think this is going to work. I'm adding instructions to test locally in PR #271 which should help your doc work significantly.

**Comment by darigovresearch** [comment]
@daveismith managed to find a work around using h3s as docsy makes subtitles links automatically so this approach would probably be the easiest than asking users to manually generate relrefs

**Comment by darigovresearch** [comment]
@daveismith & @G-Pereira is there anything else that is required for this pull request to be merged?

**Comment by daveismith** [comment]
I’m trying to figure out the proper way to do it. Using a heading doesn’t
seem right to me from markup perspective. Technically we should be using a
definition list but I haven’t had the time to figure that out yet.

**Comment by darigovresearch** [comment]
Thanks for coming back on this, yes would agree that the current approach is not perfect. However you may get more success merging this pull request and raising a new issue requesting it to be refactored the correct way & labelling it as a `good first issue`/`help wanted`. That way there is progress on this specific issue and someone who may know the answer from the community may reach the solution before you figure it out, plus you're working on additional larger scope issues so this may help allocate resources for the project like you already have done.

Very happy to (if given the right level of access to the repo) to merge this PR, set up a new issue and label it correctly to help encourage the above if that is of interest.

**Comment by daveismith** [comment]
Please feel free to set up a new issue.

**Comment by darigovresearch** [comment]
Thanks for merging the pull request, issue https://github.com/index-machines/index/issues/324 has been created but am unable to set the labels as don't have the correct permissions

**Pull request merged**
