### PR TITLE
Add STL files for corner bracket

### PR DESCRIPTION
**Pull request by mariusmotea**
I had issues finding this bracket in stock on local stores so i made them in Fusion360. 
 - It works with M5-10mm screws 
 - Are left and right because are not 20mmx20mm but 40mm x 20mm, in order to have space for the two M5 screws.
 - They fit perfectly in the v slot.
 - I think there is no real difference between this and the metal one in terms of strength.
 - Need to be printed exactly how it is positioned on the bed.
 - I can provide the Fusion project if needed.

### CODE REVIEW

**Comment by darigovresearch** [comment]
@mariusmotea we believe that the current STL files for this repository are now being built using FreeCAD, depending on if the maintainers approve this pull request, if you know FreeCAD and are able/willing to make a model, we're sure they would be happy if you were to create a FreeCAD version of the STL to upload for completeness if other people have the same issue as you.

NB if the maintainers think this STL is helpful the only suggestion we would make (if the suggestion is valid at all) is to adjust the spelling of the name from `braket` to `bracket` as this may be a typo in English. There also may be a file naming convention you may need to follow for consistence or ease of use.

**Comment by mariusmotea** [comment]
I fix the typo in the file names. I saw this is made in FreeCAD, unfortunately in this moment i don't know how to use it. I have no problem if this PR is closed, i only want to show this to maintainers since i consider to be an improvement and i don't want to keep it just for me. I look in the BOM and notice the brackets cost $20 and these seams to be the most expensive basic components. 

Here are two pictures on how they look mounted:
https://photos.app.goo.gl/wUkopym9Y2Jq2YPw7

**Comment by darigovresearch** [comment]
@mariusmotea you raise a very interesting point about bracket cost & how having a printable version would be helpful if the maintainers wish to merge this pull request. If you don't know a lot about FreeCAD and if the pull request is merged, raising an open issue to see if anyone from the community would be willing to model it may be the best course of action.

In terms of structural rigidity do you think that your print is equivalent for the application required as the original part and did you have to have any special print settings or do any post processing outside of the standard [print settings](https://docs.indexmachines.io/docs/reference/print-settings/)?

**Comment by mariusmotea** [comment]
@darigovresearch without the aluminium bracket i cannot compare but i can tell that after i remove the parts from the bed i saw how rigid they are and the only concern was to not crack when i will tight the screw strong, but even when i apply high force there where no issues . There are some benefits that aluminium bracket don't have, they fit in the V-slot perfectly so they don't allow any rotation and also the contact surface is double on one side.
I aim to place 0402 SMD's and RPi CM4 connector so i try to have a rigid frame as much as possible and for this i will need some improvements, but i think with these printed brackets  there is no loss.
I print them with PETG using 25% cubic infill pattern, 1mm walls tickness.

Probably at the end i will share more changes.

**Comment by darigovresearch** [comment]
@mariusmotea have you considered printing the parts using the printing guidelines to see if it is sufficiently rigid for the application?

This may significantly reduce complexity of sourcing the material, slicing & printing if all 3D printable parts are made from the same material

**Comment by mariusmotea** [comment]
@darigovresearch where i can find these guidelines because I can test very easy? These parts don't require too much time to be printed.

**Comment by darigovresearch** [comment]
@mariusmotea sure the print instructions can be found on the docs here - https://docs.indexmachines.io/docs/reference/print-settings/

**Comment by mariusmotea** [comment]
No issues with PLA parts as well.  While still important, infill patern is not specified. I use the same cubic infill patern.

**Comment by darigovresearch** [comment]
Thanks @mariusmotea for testing it, from our point of view having another printed part is not a big overhead and if it works as well as the metal part we would probably print it.

Do the maintainers have any thoughts on these parts and what else needs to be done for this to be merged?

**Comment by G-Pereira** [comment]
Hey @mariusmotea and @darigovresearch sorry for the enormous delay.
For this to be merged we need a FreeCAD design file, not just the STL file.
@sphawes do you think this 3d printed cornet bracket is a good idea?

**Comment by darigovresearch** [comment]
Thanks @G-Pereira thanks for coming back on the topic, as above @mariusmotea mentions that they don't know a lot about FreeCAD at this point in time. If given a blueprint for this file we can have a got but also @mariusmotea this may be a good excuse to learn a new tool on a simple model you've already made

**Comment by stuartpittaway** [comment]
The metal corner brackets are easily available, for instance Amazon and Aliexpress

https://amzn.to/3qgahty

https://s.click.aliexpress.com/e/_A7Y8NB

Neither are highly priced.

**Comment by nkappler** [comment]
> 
> 
> The metal corner brackets are easily available, for instance Amazon and Aliexpress
> 
> https://amzn.to/3qgahty
> 
> https://s.click.aliexpress.com/e/_A7Y8NB
> 
> Neither are highly priced.

These are both the wrong kind of brackets, since these little nibbons won't allow installing them perpendicular to the slot,
as required with the current design
grafik

**Comment by stuartpittaway** [comment]
The nibs can be removed, but they do still work and fix securely even with the nibs

**Comment by martinbogo** [comment]
I concur with Stuart.  Even with nibs they work perpendicularly without
issue.  The nibs are also very easy to sand down.

**Comment by sphawes** [comment]
Going to close this PR. We're using mostly plastic for this machine, but these brackets are what gives us a really excellent amount of rigidity, and lets us get away with making this much of it out of plastic. That being said, @mariusmotea I'd love to see how well your machine works without metal brackets holding the extrusion together!

**Comment by mariusmotea** [comment]
It works fine, 90% of the SMD's are 0402 and are placed with high precision, see: https://www.youtube.com/watch?v=-GKsQrw6zaA

**Comment by darigovresearch** [comment]
@mariusmotea nice video, happy to see more videos of the PnP in the wild!

**Pull request closed without merging**
