### PR TITLE
Mobo REV03 Silkscreen updates, Test Pads, and Elec Cap Shift

### PR DESCRIPTION
**Pull request by sphawes**
updated spelling in silkscreen labels, added test pads for bed of nails jig, moved electrolytic caps under stepper drivers over a bit so that they don't touch pins sticking out the bottom.

### CODE REVIEW

**Review by G-Pereira — CHANGES_REQUESTED** [review]
These traces need to be re-routed:
image

**Comment by atanisoft** [comment]
If those two R were swapped it would also provide a better routing possibly

**Comment by sphawes** [comment]
just fixed this! was a problem with how my kicad build was importing the mosfet, my netlist was all screwy and had incorrect ratsnest lines. DRC only shows courtyard overlapping from the stepper motor drivers, and a couple pads built into the USBC connector.

**Comment by daveismith** [comment]
@sphawes I would consider adding a BOOT1 testpoint so that you can trigger the device into DFU mode. You may not use it, but at the end of the day I'm sure you would prefer to have an extra TP vs not having one that would make life easier.

Additionally, I might put actual TPs for the various voltage rails to get a good connection in case the cupped pogos don't work as well as might be expected for power transfer (especially with current).

**Comment by martinbogo** [comment]
For automated testing, I would definitely appreciate a BOOT1 testpoint.

Also, hi... I'm back from working on $SECRETPROJECT at work.  Sorry I've
been away.

**Comment by sphawes** [comment]
added testpoint for boot0, and dedicated test points for all power rails and ground!

**Pull request merged**
