### PR TITLE
Remove Auto Commit

### PR DESCRIPTION
**Pull request by daveismith**
Removing Automatic Commit of the Artifacts, instead upload the artifact at the opposite end.

### CODE REVIEW

**Comment by sphawes** [comment]
Awesome! Is the easiest way to get to the artifacts generated by clicking on the green check next to the commit and hunting for it in there, or just going to the Actions tab and trying to find the corresponding action? Trying to find a clean way to tell folks in the wiki how to find the artifacts for any given time the action runs.

**Comment by stuartpittaway** [comment]
Not sure I'm in favour of this, I do like the existing EXPORT folder, I don't find the Artifacts in github very easy to find/use.

**Comment by daveismith** [comment]
@stuartpittaway - This was where we ended up after some discussion between @Jnesselr , @sphawes  and myself. The main reasons to do this are to get rid of some of the CI conflicts we're getting when multiple CI elements try to commit back to the repo as well as reducing the size of the repo (we're coming up on the 1GB soft limit github imposes). 

The part that comes after this (not implemented yet) is to automatically attach the artifacts to proper releases. It may be possible to have the actions publish to a wiki page with a link to the latest builds so that we could link through there indirectly.

**Comment by stuartpittaway** [comment]
Have you thought about splitting up the repo?  Its not great that the mobo gets a new build hash everytime a non-related change is committed etc.

**Comment by sphawes** [comment]
Per the 2021-10-04 dev call, we'll merge this in! @daveismith I'll make a new issue about doing the second half of this and getting the artifacts to generate. Would be quite excellent to have links to the artifacts auto populate in the docs website. Of course this only makes the source very easy to find for tagged commits, but that's what most folks will be looking for anyway.

**Pull request merged**
