### PR TITLE
Updated readme file and new index image

### PR DESCRIPTION
**Pull request by stuartpittaway**
I've updated the readme to correct a few typos and added new image of the Index based on the FreeCad models.

Added cross references to the Index documentation site for 3d printing.

### CODE REVIEW

**Comment by daveismith** [comment]
@sphawes - this is an update to the main readme. Please take a look at update with your thoughts.

**Comment by ocouch** [comment]
@stuartpittaway  Have a look at #318 Stephen included an updated hero image there too.

**Comment by stuartpittaway** [comment]
Looks like this can be closed off then, as Stephens image is newer/up to date.

**Comment by ocouch** [comment]
@stuartpittaway Image maybe, does the same go for your typo corrections and links?

**Comment by stuartpittaway** [comment]
Those are still valid

**Pull request closed without merging**
