### PR TITLE
Creation of 3d print calibration shape specific for Index build

### PR DESCRIPTION
**Pull request by stuartpittaway**
This commit creates a 3d print shape, containing the common M3 and M5 nuts and bolt holes along with a typical 20x20 hole for the extrusion.  Users can print this to ensure calibration of 3d printed parts before embarking on 48hours+ of printing for the real components.

References issue #320

### CODE REVIEW

**Comment by stuartpittaway** [comment]
image

**Comment by ocouch** [comment]
Might be worth adding a large thin octagon test print too (to test for parralellism and dimensional accuracy), which should be printed as large as possible on the user's printer to check for large scale geometric precision in X&Y axes. A few layers high to check for elephant's foot effects.

A Z axis calibration print of some kind would be good too.

**Comment by stuartpittaway** [comment]
> Might be worth adding a large thin octagon test print too (to test for parralellism and dimensional accuracy), which should be printed as large as possible on the user's printer to check for large scale geometric precision in X&Y axes. A few layers high to check for elephant's foot effects.
> 
> A Z axis calibration print of some kind that can test the Z axis at multiple X,Y locations would be good too.

I agree with the comments, although those parts are likely to already exist on thingiverse etc.  I was trying to produce a test specific to the needs of Index - particularly the 20x20 rail, which I have issues with due to the bridging on one of the sides - the "droop" of the bridge, makes the rails difficult to fit.

**Comment by ocouch** [comment]
Yeah totally - this is a very good addition and looks like a good calibration print, sorry, was just thinking more broadly it would be good to have a standard calibration process to help make sure less experienced makers still get a good result off their printers.

**Comment by darigovresearch** [comment]
This is a great idea and always very helpful with respect to projects that require 3D printed parts to test before putting in multiple hours of time and material. Another project that does this well is the [openflexure microscope](https://openflexure.org/projects/microscope/).

**Comment by G-Pereira** [comment]
Thanks @stuartpittaway this is a good idea! Also thanks for your reviews @ocouch and @darigovresearch !

We are fine tuning hole diameters and we need to wait for that so this part matches whatever we choose to add to our design.

**Comment by G-Pereira** [comment]
Btw the 2020 extrusion hole won't be printed in that orientation so that feature of the part should be layed flat on that part. Doing that also help reduce the part volume which is important since this part is 100% wasted plastic after calibration.
Any ideas to reuse this part to be a little bit environment friendlier?

**Comment by darigovresearch** [comment]
Thanks for the guidance @G-Pereira, some of the holes can be placed either under the bridge or on the bridge to reduce surface area and volume. This part may be considered like a badge of honour for building an index (like putting it on your wall or like a pendent on of piece of jewellery. Also depending on any other additional machines/extensions that are built and if they have test prints as well it could then generate a tessellated design on the wall or part of the machine. Potentially can be used as a mount to hold tools onto for debugging the index as well (like tweezers etc).

**Comment by stuartpittaway** [comment]
I originally was going to call it the index coin, but then I added on the 20x20 hole and it wasn't coin shaped anymore!

@G-Pereira  I orientated the 20x20 hole to print the same way as the front legs do. Being a square it's always going to have one side bridged, unless it's on the Z axis.

This isn't possible with the current front leg design. I also find the 20x20 holes print very tight on the current design for both front and rear legs.

**Comment by G-Pereira** [comment]
@darigovresearch @stuartpittaway  Those are good ideas for the usage of such part, making it a badge with "Index PnP" embossed which can be mounted onto the machine is nice! Maybe the 2020 hole can slide into one of the rails and sit in that position with one of the screw holes to hold it in place!

**Comment by stuartpittaway** [comment]
I know, I'll get it to fit on the spare bolt holes on the front of the right leg (left leg has the umbilical mount).

See what I can do!

**Comment by stuartpittaway** [comment]
This should now be closed as @SyberxSpace is doing a much nicer version

**Pull request closed without merging**
