### PR TITLE
docs: Adds initial contributing page to docs

### PR DESCRIPTION
**Pull request by darigovresearch**
Initial content comes from https://github.com/sphawes/index/blob/master/CONTRIBUTING.md as a placeholder to adjust if required.

### CODE REVIEW

**Comment by daveismith** [comment]
@sphawes, I'm not sure if you want to move the contributing page off of GitHub or if we should simply link to it here. To date this has been more of an assembly guide but we are starting to expand out the content with a glossary.

**Comment by darigovresearch** [comment]
@daveismith that's a good point, I don't think moving it off of GitHub is a good idea as some people may come across the repository first and need guidance. That said it's also good to have it in the documentation as some people may find the documentation first and having some guidance there (it doesn't have to be the same as the one in the repository) would bring some benefit as well than it only being for assembly.

@sphawes happy to take your guidance on this to adjust the PR if required, just thought it was a good start and can be adjusted  later if you wish the contributing guideline on the docs to be targeted to different forms of contribution such as openly saying filling in the content of the documentation would be helpful.

**Comment by darigovresearch** [comment]
Is there anything else needed from us on this issue to merge this pull request?

**Comment by daveismith** [comment]
I think it’s hanging here because I’m not sure Stephen wants to move it to
the docs.

**Comment by darigovresearch** [comment]
Got it thanks, have updated the PR to reflect the current state of the guidelines

**Comment by sphawes** [comment]
Thank you for this @darigovresearch! We've got the contributing.md page directing to the wiki page!

**Pull request closed without merging**
