### PR TITLE
Ring light rev04

### PR DESCRIPTION
**Pull request by ttahsin-bey**
### Changes to Ringlight PCB:

* Each WS2812B has now it's own capacitor.
* Level-Shifter added.
* All components have part-numbers from LCSC and JLCPCB (if possible "basic" parts are being used).
* Horizontal or vertical JST-Connector can be used (on back side of pcb).

image

image

image

image

### Changes to Printed Parts:

All:
* Orientation corrected (now the front side is (mostly) where the debossed text is located).
* Every object that modifies a body (pocket, pad, fillets, chamfer, etc.) has a label, explaning the use of this operation.
* All parts have a spreadsheet, where design parameters can be entered (parametric design).
* All sketches are now fully constrained.
* All bodies are without exclamation marks (no warnings anymore...).
* All bodies are now using the "refine=true"-method

FDM-0014:
* More space for camera body

FDM-0015 and FDM-0019:
* Small cutouts added for C8 of ringlight interfering with support surface (only one cutout would be needed...)
Remark: It may be mentioned in the documents, that the 1mm-diffuser may be printed with transparent filament...

FDM-0020:
* Space for camera body and lens increased (according the PR #393)
* Added cutout for horizontal connector of ringlight pcb (screw at this position should now be M2,5*5).

Down-looking camera module:
image

Up-looking camera module:
image

### CODE REVIEW

**Comment by stuartpittaway** [comment]
Thank you for this @ttahsin-bey we've been speaking over on the discord chat about the changes.

The changes to the camera mounts are based on the updated design I made in PR #393 

We've also spoken about only using a single horizontal connector on the ring light to avoid having multiple parts/BOM costs etc.  What do you think?

Could @G-Pereira review the KiCad changes?

@sphawes this is the updated ring light design.

**Comment by theacodes** [comment]
We were chatting about this in the discord and wanted to offer up some of that here:

It might be worth considering the SK9822 / APA102C ([Dotstar](https://www.adafruit.com/product/2343)) LEDs. They have several advantages over the Neopixels - they are specified at 3.3V and they use a SPI-compatible protocol so they don't require a complicated software driver. They require one more signal line over the Neopixels, but in my experience that really hasn't been an issue. They would also only require one bulk capacitor between 10uF and 47uF for this application. Finally, if RGB isn't needed, Dotstars have [monochrome variants](https://www.adafruit.com/product/2351).

I've got a lot of experience with the Dotstars and I'm happy to help however I can if y'all think this might be a good route to go. :)

**Comment by ocouch** [comment]
You might like to consider using a later version of the WS2812s. Newer versions require no external components - not even filter capacitors on the power rail.

image

https://datasheet.lcsc.com/lcsc/2006151006_Worldsemi-WS2812B-B_C114586.pdf

**Comment by G-Pereira** [comment]
This is interesting as it solves the issue with signal threshold voltage while using a 3.3V signal since the ViH of these LEDs is 2.7V. It effectively reduces the part count. The downside is that it requires a pcb change as this LED is not pin compatible.

**Comment by G-Pereira** [comment]
I am sorry it is pin-compatible

**Comment by sphawes** [comment]
Hey @ttahsin-bey! Sorry for the delay on this getting looked at, but damn, nice changes!

There's a couple things that need to be changed in it (standardizing footprints to 0805, uprevving to KiCad v6, fixing any collisions with unlocked CAD files), so I've make a new branch in the main repo so everyone can collaborate, add these changes to it, and we can make the PR from that instead of from your fork. The link is [here](https://github.com/index-machines/index/pull/429). I'll close this one so we can continue in the new PR.

**Pull request closed without merging**
