### PR TITLE
Z Gantry changes/belt position

### PR DESCRIPTION
**Pull request by stuartpittaway**
screenshot3
Whilst constructing the index machine, I became aware of the Z axis requiring the belt and pulley/gear assemblies to be right on the end of the stepper motor shaft.

This change aims to remove that offset and bring the belt near to the X gantry front, which reduces tension in the belts and motor shaft.

In addition to this, the change provides two new parts which can be kept permanently attached to the linear rail blocks.

This prevents the whole Z belt and blocks being disturbed when the devices attached to the Z axis change - for instance swapping a PNP head with a solder paste dispenser.

This change also corrects issues raised in #327

The change also removes the need for a 35mm M5 machine screw, instead using the 25mm screw already in use.

This change adds these two new parts
"FDM-0040","z-gantry-backplate-left"
"FDM-0041","z-gantry-backplate-right"

An updated version of FDM-0038 (z-idler-spacer) is included but is not really required - instead a simple M5 washer should be used.

I have also updated the STL export script to spot when the part number doesn't match the filename and report this as an error.

The X gantry front plate has also been corrected to fix issue #331 in addition a large oval cut out has been added which reduces print time by about 30 minutes.

screenshot1
screenshot2
screenshot3

### CODE REVIEW

**Comment by G-Pereira** [comment]
I like the fact this makes it possible to swap heads without messing with the Z belt. But I'll leave this for @sphawes to review

**Comment by daveismith** [comment]
@stuartpittaway - in the existing design the belt is inserted into the toothed section from the front which means you can accurately select the length and tension. I'm guessing here you're relying on the adjustability of the motor to tension after installation since you can't really insert the belt while the pieces are on the linear rail blocks.

**Comment by stuartpittaway** [comment]
> @stuartpittaway - in the existing design the belt is inserted into the toothed section from the front which means you can accurately select the length and tension. I'm guessing here you're relying on the adjustability of the motor to tension after installation since you can't really insert the belt while the pieces are on the linear rail blocks.

Yes, although the length of the belt should be the same for all, so easily cut to length before assembly

**Comment by sphawes** [comment]
@stuartpittaway This is an AWESOME edit, and an awesome idea. Thank you so much for the update!

What do you think about having two, diagonal mounting screws pass through the motor mount, instead of just one? That way the back plane prints wouldn't be able to rotate freely on one screw when the motor mount/other head mount is removed. Might also make exchanging tools a bit more repeatable if the back plane can't move during the tool change process.

Also if the M5 washer can act as a spacer, I think that's an excellent idea and we can just scrap FDM-0038!

**Comment by mmb-davidsmith** [comment]
In addition, how does the limit switch engage? Would it make sense to have the gantry backplate set up to trigger the end stop instead of using the actual tool holder?

**Comment by daveismith** [comment]
In addition, how does the limit switch engage? Would it make sense to have the gantry backplate set up to trigger the end stop instead of using the actual tool holder?

**Comment by stuartpittaway** [comment]
The limit switch triggers on the back plate just fine.

Happy to change the mounting screws to diagonal, do you want me to do it??

**Comment by sphawes** [comment]
@stuartpittaway yes, that would be excellent, thank you!

**Comment by stuartpittaway** [comment]
@sphawes I've put the two bolt holes on to bottom half of the bearing block rather than diagonally - that way, you can still remove the Z carriage without removing the stepper mounter bolts.

Please review.

**Comment by sphawes** [comment]
@stuartpittaway brilliant idea, that makes a ton of sense. Weirdly there was a merge conflict with the BOM csv file that i would have expected git to manage, but it didnt. i made it updated to your version.

In the future, if you could have a Contributor on the repo lock the CAD files youd like to work on, that would be excellent. Unfortunately FreeCAD files don't merge well, so we need to utilize more of a "checkout" system where one person works on them at a time, otherwise someone's work needs to be erased. You can read about it here: https://github.com/index-machines/index/wiki/Contributing

This is an awesome PR, thank you so much for your edits! Going to merge this now.

**Pull request merged**
